@startuml
skinparam actorStyle awesome
left to right direction
actor "Nasa API" as API
actor "Utente" as user
rectangle {
  usecase "apri app" as UC1
  usecase "Aggiorna dati" as UC2
}

user --> UC1
API --> UC2

@enduml 