@startuml
skinparam actorStyle awesome
left to right direction

actor Utente as user
actor API as api

rectangle "Applicazione" {
  user -- (Apri App)
  (Apri App) --> (Visualizza Foto)
  (Seleziona Foto) --> (Vedi Informazioni)
  (Visualizza Foto) --> (Seleziona Foto)

  (Seleziona Foto) --> (Doppio Tap Salva Foto)
}
(Visualizza Foto)--api
@enduml